#!/bin/bash
clear
sudo apt install openjdk-17-jdk -y
sudo apt install gradle -y
sudo apt install tree -y
clear
clear
echo -e "\e[1;31mSelect Java version 17\e[0m"
read -p "Press Enter to continue..."
clear
echo -e "\e[1;31mSelect Java version 17\e[0m"
sudo update-alternatives --config java
cd ~
mkdir MyGradleApp
cd MyGradleApp
gradle init --type java-application
tree


# Overwrite build.gradle with embedded content
cat > build.gradle <<'EOF'
/*
 * This build file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.4.1/userguide/tutorial_java_projects.html
 */

// Apply the java plugin to add support for Java
apply plugin: 'java'

// Apply the application plugin to add support for building an application
apply plugin: 'application'

// In this section you declare where to find the dependencies of your project
repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenCentral()
}

dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    compile 'com.google.guava:guava:23.0'

    // Use JUnit test framework
    
    testImplementation 'junit:junit:4.13.2'
}

mainClassName = 'com.example.App'

task hello {
    doLast {
        println 'Hello, Gradle!'
    }
}

task greet(dependsOn: build) {
doLast {
println 'Build is complete! Time to celebrate!'
}
}

group = 'com.example'
version = '1.0'
EOF
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export PATH=$JAVA_HOME/bin:$PATH
gradle hello
./gradlew greet
