#!/bin/bash
clear
sudo apt install openjdk-11-jdk -y
sudo apt install maven
sudo apt install tree
sudo apt install gradle -y
clear
echo -e "\e[1;31mSelect Java version 11\e[0m"
read -p "Press Enter to continue..."
clear
echo -e "\e[1;31mSelect Java version 11\e[0m"
sudo update-alternatives --config java
clear
echo "Enter Maven project name:"
read name
cd
rm -rf $name
    mvn archetype:generate -DgroupId=com.example -DartifactId=$name -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
cd $name
tree
cat > pom.xml <<EOF
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>${name}</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>${name}</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
  <plugins>
  	<plugin>
  		<groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <version>3.8.1</version>
      <configuration>
      	<source>11</source>
      	<target>11</target>
      </configuration>
  	</plugin>
  	
  	<plugin>
  		<groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-surefire-plugin</artifactId>
      <version>2.22.2</version>
  	</plugin> 
  </plugins>
  </build>
</project>
EOF
mvn compile
mvn package
java -cp target/$name-1.0-SNAPSHOT.jar com.example.App
cd 
echo "Enter Gradle project name:"
read name2
mkdir $name2
cd $name2
gradle init --type java-application
SOURCE=~/$name/src/main/java/com/example/App.java
TARGET=~/$name2/src/main/java/com/example/App.java
mkdir ~/$name2/src/main/java/com ~/$name2/src/main/java/com/example
cp $SOURCE $TARGET
cat > build.gradle <<'EOF'
/*
 * This build file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.4.1/userguide/tutorial_java_projects.html
 */

// Apply the java plugin to add support for Java
apply plugin: 'java'

// Apply the application plugin to add support for building an application
apply plugin: 'application'

// In this section you declare where to find the dependencies of your project
repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenCentral()
}
dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    compile 'com.google.guava:guava:23.0'

    // Use JUnit test framework
    
    testImplementation 'junit:junit:4.13.2'
}

mainClassName = 'com.example.App'

task hello {
    doLast {
        println 'Hello, Gradle!'
    }
}

task greet(dependsOn: build) {
doLast {
println 'Build is complete! Time to celebrate!'
}
}

group = 'com.example'
version = '1.0'
EOF

cat > ./src/test/java <<'EOF'
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import com.example.App;
public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
EOF

gradle build

